name: front_spaced_repetition_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  toastification: ^3.0.3
  responsive_layout_grid: ^1.1.2
  file_picker: ^10.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/